"""
PDF Report Generator for WhatsApp Chat Analyzer
Uses ReportLab to produce a professional styled PDF report.
"""
import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from datetime import datetime
from . import analyzer as helper


def _make_color(hex_str):
    """Convert hex color string to reportlab color."""
    hex_str = hex_str.lstrip('#')
    r, g, b = tuple(int(hex_str[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    return colors.Color(r, g, b)


# Theme colors
PRIMARY = _make_color('3b82f6')
ACCENT = _make_color('0ea5e9')
GREEN = _make_color('10b981')
PINK = _make_color('ec4899')
PURPLE = _make_color('8b5cf6')
DARK = _make_color('0f172a')
MUTED = _make_color('64748b')
LIGHT_BG = _make_color('f8fafc')
WHITE = colors.white

CHART_COLORS = [PRIMARY, ACCENT, GREEN, _make_color('6366f1'), PURPLE, PINK, _make_color('f43f5e'), _make_color('facc15')]


def generate_pdf(df, selected_user='Overall'):
    """Generate a full PDF report and return BytesIO buffer."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=30 * mm,
        leftMargin=30 * mm,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CoverTitle', parent=styles['Title'],
        fontSize=28, leading=34, textColor=DARK,
        fontName='Helvetica-Bold', alignment=TA_CENTER,
        spaceAfter=10,
    )
    subtitle_style = ParagraphStyle(
        'CoverSubtitle', parent=styles['Normal'],
        fontSize=13, textColor=MUTED,
        fontName='Helvetica', alignment=TA_CENTER,
        spaceAfter=6,
    )
    section_style = ParagraphStyle(
        'SectionHead', parent=styles['Heading2'],
        fontSize=16, textColor=DARK,
        fontName='Helvetica-Bold', spaceBefore=20, spaceAfter=10,
        borderColor=PRIMARY, borderWidth=0, borderPadding=0,
    )
    body_style = ParagraphStyle(
        'BodyText2', parent=styles['BodyText'],
        fontSize=10, textColor=DARK,
        fontName='Helvetica', leading=14,
    )
    metric_label_style = ParagraphStyle(
        'MetricLabel', parent=styles['Normal'],
        fontSize=9, textColor=MUTED,
        fontName='Helvetica',
    )
    metric_value_style = ParagraphStyle(
        'MetricValue', parent=styles['Normal'],
        fontSize=18, textColor=DARK,
        fontName='Helvetica-Bold',
    )

    elements = []

    # ═══════════ COVER PAGE ═══════════
    elements.append(Spacer(1, 80))
    elements.append(Paragraph("WhatsApp Chat Analysis", title_style))
    elements.append(Paragraph("Comprehensive Analytics Report", subtitle_style))
    elements.append(Spacer(1, 15))
    elements.append(HRFlowable(width="60%", thickness=2, color=PRIMARY, spaceAfter=15, spaceBefore=5))

    user_label = "All Users (Overall)" if selected_user == 'Overall' else f"User: {selected_user}"
    elements.append(Paragraph(f"Analysis for: <b>{user_label}</b>", subtitle_style))

    # Date Range
    date_min = str(df['date'].min())[:10] if len(df) > 0 else 'N/A'
    date_max = str(df['date'].max())[:10] if len(df) > 0 else 'N/A'
    elements.append(Paragraph(f"Date Range: {date_min} → {date_max}", subtitle_style))
    elements.append(Paragraph(f"Report Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style))

    elements.append(Spacer(1, 50))
    elements.append(Paragraph("Generated by WhatsApp Analyzer Pro", ParagraphStyle(
        'Footer', parent=styles['Normal'], fontSize=9, textColor=MUTED, alignment=TA_CENTER,
    )))
    elements.append(PageBreak())

    # ═══════════ TOP STATISTICS ═══════════
    num_msg, words, num_media, num_link, active_days = helper.fetch_stats(selected_user, df)

    elements.append(Paragraph("📊 Top Statistics", section_style))
    elements.append(Spacer(1, 5))

    stats_data = [
        ['Total Messages', 'Total Words', 'Media Shared', 'Links Shared', 'Active Days'],
        [f'{num_msg:,}', f'{words:,}', f'{num_media:,}', f'{num_link:,}', f'{active_days:,}'],
    ]
    stats_table = Table(stats_data, colWidths=[90] * 5)
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('FONTSIZE', (0, 1), (-1, 1), 14),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BACKGROUND', (0, 1), (-1, -1), LIGHT_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(stats_table)
    elements.append(Spacer(1, 20))

    # ═══════════ SENTIMENT ANALYSIS ═══════════
    elements.append(Paragraph("💬 Sentiment Analysis", section_style))
    sentiment_data = helper.sentiment_analysis(selected_user, df)

    elements.append(Paragraph(
        f"<b>Overall Sentiment Score:</b> {sentiment_data['overall_score']} &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"<b>Primary Sentiment:</b> {sentiment_data['primary_sentiment']}",
        body_style
    ))
    elements.append(Spacer(1, 10))

    if sentiment_data['breakdown']:
        # Table showing top sentiments
        top_sentiments = sentiment_data['breakdown'][:10]  # Top 10
        sent_header = ['Sentiment', 'Count', 'Percentage']
        sent_rows = [[s['sentiment'], f"{s['count']:,}", f"{s['percent']}%"] for s in top_sentiments]

        sent_table_data = [sent_header] + sent_rows
        sent_table = Table(sent_table_data, colWidths=[150, 100, 100])
        sent_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PURPLE),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('BACKGROUND', (0, 1), (-1, -1), LIGHT_BG),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ]))
        elements.append(sent_table)
    elements.append(Spacer(1, 20))

    # ═══════════ RESPONSE TIME ═══════════
    elements.append(Paragraph("⏱️ Response Time Analysis", section_style))
    rt_data = helper.response_time_analysis(selected_user, df)

    elements.append(Paragraph(
        f"<b>Overall Average Response Time:</b> {rt_data['overall_avg_minutes']} minutes &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"<b>Fastest:</b> {rt_data['fastest_user']} &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"<b>Slowest:</b> {rt_data['slowest_user']}",
        body_style
    ))
    elements.append(Spacer(1, 8))

    if rt_data['per_user']:
        rt_header = ['User', 'Avg Response Time (min)']
        rt_rows = [[u['user'], f"{u['avg_minutes']}"] for u in rt_data['per_user']]
        rt_table = Table([rt_header] + rt_rows, colWidths=[200, 150])
        rt_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ]))
        elements.append(rt_table)
    elements.append(Spacer(1, 20))

    # ═══════════ NIGHT OWL VS EARLY BIRD ═══════════
    elements.append(Paragraph("🌙 Night Owl vs Early Bird", section_style))
    noe_data = helper.night_owl_early_bird(selected_user, df)

    if noe_data['per_user']:
        noe_header = ['User', '🌅 Morning', '☀️ Afternoon', '🌆 Evening', '🌙 Night', 'Type']
        noe_rows = []
        for u in noe_data['per_user']:
            user_type = noe_data['classification'].get(u['user'], 'N/A')
            noe_rows.append([
                u['user'],
                f"{u['Morning']:,}", f"{u['Afternoon']:,}",
                f"{u['Evening']:,}", f"{u['Night']:,}",
                user_type,
            ])
        noe_table = Table([noe_header] + noe_rows, colWidths=[90, 70, 70, 70, 70, 80])
        noe_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), _make_color('6366f1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ]))
        elements.append(noe_table)
    elements.append(Spacer(1, 20))

    # ═══════════ AVERAGE MESSAGE LENGTH ═══════════
    elements.append(Paragraph("📏 Average Message Length", section_style))
    aml_data = helper.avg_message_length(selected_user, df)

    if aml_data:
        aml_header = ['User', 'Avg Words per Message']
        aml_rows = [[u['user'], f"{u['avg_words']}"] for u in aml_data]
        aml_table = Table([aml_header] + aml_rows, colWidths=[200, 150])
        aml_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), GREEN),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ]))
        elements.append(aml_table)
    elements.append(Spacer(1, 20))

    # ═══════════ ACTIVITY STREAK ═══════════
    elements.append(Paragraph("🔥 Activity Streak", section_style))
    streak_data = helper.activity_streak(selected_user, df)

    streak_info = [
        ['Longest Streak', 'Current Streak', 'Total Active Days'],
        [
            f"🔥 {streak_data['longest_streak']} days",
            f"📅 {streak_data['current_streak']} days",
            f"✅ {streak_data['total_active_days']} days",
        ],
    ]
    streak_table = Table(streak_info, colWidths=[150, 150, 150])
    streak_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), _make_color('f43f5e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTSIZE', (0, 1), (-1, 1), 14),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BACKGROUND', (0, 1), (-1, -1), LIGHT_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(streak_table)
    elements.append(Spacer(1, 20))

    # ═══════════ MOST COMMON WORDS ═══════════
    elements.append(Paragraph("📝 Most Common Words", section_style))
    common_words_df = helper.most_common_word(selected_user, df)

    if not common_words_df.empty:
        cw_header = ['Word', 'Count']
        cw_rows = [[str(row[0]), f"{row[1]:,}"] for _, row in common_words_df.head(15).iterrows()]
        cw_table = Table([cw_header] + cw_rows, colWidths=[200, 150])
        cw_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PURPLE),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.9, 0.9)),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ]))
        elements.append(cw_table)
    elements.append(Spacer(1, 30))

    # ═══════════ FOOTER ═══════════
    elements.append(HRFlowable(width="100%", thickness=1, color=MUTED, spaceAfter=10))
    elements.append(Paragraph(
        "This report was generated by <b>WhatsApp Analyzer Pro</b>. "
        "All metrics are computed from the uploaded chat export data.",
        ParagraphStyle('FooterNote', parent=styles['Normal'], fontSize=8, textColor=MUTED, alignment=TA_CENTER)
    ))

    # Build
    doc.build(elements)
    buffer.seek(0)
    return buffer
